apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airraid-shared-rwx
  labels:
    app: airraidanalysis
    storage-profile: multi-node
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
